config/routes.rb
HackedNews::Application.routes.draw do
  root to: "articles#index"

  devise_for :users
  get 'profile(/:user_id)' => 'users#show', :as => :profile

  resources :articles, :comments, :votes

  get "newest" => "articles#newest"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :url, :user_id

  has_many :votes, as: :votable
  has_many :comments
  belongs_to :user

  validates_presence_of :title, :url
  validates_uniqueness_of :url
  validates :url, :format => URI::regexp(%w(http https))

  def num_votes
    self.votes.count
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :user_id, :article_id

  has_many :votes, as: :votable
  belongs_to :article
  belongs_to :user

  validates_presence_of :text

  def comment_votes
    self.votes.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body

  validates :username, presence: true, uniqueness: true

  has_many :votes
  has_many :articles
  has_many :comments

  def already_voted_on?(id)
    self.votes.where(votable_id: id).count > 0
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :value, :votable_id, :votable_type, :user_id

  belongs_to :votable, polymorphic: true
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  def index
    @articles = Article.all.sort { |a,b| b.num_votes <=> a.num_votes }
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    @article["user_id"] = current_user.id

    if @article.save
      flash[:notice] = @article.title + " was added."
      redirect_to root_path
    else
      flash[:error] = "An error occurred, please try again."
      redirect_to new_article_path
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments.sort { |a,b| b.comment_votes <=> a.comment_votes }
  end

  def newest
    @articles = Article.order("created_at desc")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new

  end

  def create
    @comment = Comment.new(params[:comment])

    if @comment.save
      flash[:notice] = "Your comment was added."
      redirect_to article_path(id: @comment.article_id)
    else
      flash[:error] = "An error occurred, please try again."
      redirect_to article_path(@article)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:user_id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @vote = Vote.new
  end

  def create
    if current_user.already_voted_on? params[:votable_id]
      flash[:error] = "You already voted!"
      redirect_to :back
    else
      @vote = Vote.new(params[:vote])
      @vote.votable_id = params[:votable_id]
      @vote.value = params[:value]
      @vote.user_id = current_user.id
      @vote.votable_type = params[:votable_type]
      @vote.article_id = params[:article_id]



      if @vote.save
        if @vote.votable_type == "Article"
          redirect_to root_path
        else
          redirect_to :back
        end
      else
        flash[:error] = "There was an error. Your vote was not added."
        if @vote.votable_type == "Article"
          redirect_to root_path
        else
          redirect_to :back
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, class: "gravatar")
  end
end

app/views/articles/index.html.erb
<div class="articles">
  <% @articles.each do |article| %>
  <div class="title">
    <%= link_to image_tag('votearrow.gif'), votes_path(votable_id: article.id, value: 1, votable_type: "Article"), method: :post %>
    <%= link_to article.title, article.url %>
    <%= image_tag("http://www.google.com/s2/favicons?domain_url=" + article.url) %>
  </div>
  <div class="submitted-by">
    <%= pluralize(article.votes.count, 'vote') %>
    by <%= link_to article.user.username, profile_path(user_id: article.user.id) %>
    <%= time_ago_in_words(article.created_at) %> ago |
  </div>
  <div class="comments">
    <%= link_to pluralize((article.comments.count), 'comment'), article_path(id: article.id) %>
  </div>
  <br><br>
  <% end %>
</div>
<br><br>

app/views/articles/new.html.erb
<h3>Submit Article</h3>
<%= simple_form_for(@article, html: { class: "form-horizontal" }) do |f| %>
    <%= f.input :title, required: false %>
    <%= f.input :url, required: false %>
    <br><br>
    <%= f.submit "Submit", class: "btn" %>
<% end %>

app/views/articles/newest.html.erb
<div class="articles">
  <% @articles.each do |article| %>
      <div class="title">
        <%= link_to image_tag('votearrow.gif'), votes_path(value: 1), method: :post %>
        <%= link_to article.title, article.url %>
        <%= image_tag("http://www.google.com/s2/favicons?domain_url=" + article.url) %>
      </div>
      <div class="submitted-by">
        <%= pluralize(article.votes.count, 'vote') %>
        by <%= link_to article.user.username, profile_path(user_id: article.user.id) %>
        <%= time_ago_in_words(article.created_at) %> ago |
      </div>
      <div class="comments">
        <%= link_to pluralize((article.comments.count), 'comment'), article_path(id: article.id) %>
      </div>
      <br><br>
  <% end %>
</div>

app/views/articles/show.html.erb
<div id="article-content">
    <h4 id="article-show-title"><%= @article.title %></h4>
    <div id="show-link">(<%= link_to @article.url %>)</div>
    <br><br>
    <%= simple_form_for(@comment, html: { class: "form-horizontal" }) do |f| %>
        <%= f.input :text, as: :text, label: false, input_html: {rows: 4} %><br>
        <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
        <%= f.input :article_id, as: :hidden, input_html: { value: @article.id } %>
        <%= f.submit "Add Comment", class: "btn" %>
    <% end %>

    <div id="comments">
      <% @comments.each do |comment| %>
        <% user = User.where("id = ?", comment.user_id)[0] %>
        <%= link_to image_tag('votearrow.gif'), votes_path(votable_id: comment.id, value: 1, votable_type: "Comment", article_id: @article.id), method: :post %>
        <%= link_to user.username, profile_path(user_id: user.id) %>
        <%= time_ago_in_words(comment.created_at) %> ago<br>
        <%= comment.text %><br>
        <%= pluralize(comment.votes.count, 'vote') %>
        <br><br>
      <% end %>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <%= link_to "HackedNews", root_path, class: "brand" %>
    <ul class="nav">
      <li><%= link_to "Newest", newest_path %></li>
      <li><%= link_to "Submit", new_article_path %></li>
    </ul>
    <ul class="nav pull-right">
      <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackedNews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
  <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>HackedNews</h1>

app/views/users/show.html.erb
<div id="gravatar"><%= gravatar_for @user %></div>
<h3 id="username"><%= @user.username %></h3><br><br>
<h3 id="created">Created: </h3>
<span><%= time_ago_in_words(@user.created_at) %> ago</span>
<h3>Articles:</h3>
<% @user.articles.each do |article| %>
    <%= link_to article.title, article.url %><br>
<% end %>
<h3>Comments:</h3>
<% @user.comments.each do |comment| %>
    On <%= link_to comment.article.title, comment.article.url %><br>
    <%= comment.text %><br><br>
<% end %>